# Data Celeaning Transport Dataset

In [1]:
import numpy as np
import pandas as pd

## 1. Sustainable Lifestyle Rating Dataset

In [2]:
sustainableLifestyle_df = pd.read_csv('data/lifestyle_sustainability_data.csv')
sustainableLifestyle_df.head()

,ParticipantID,Age,Location,DietType,LocalFoodFrequency,TransportationMode,EnergySource,HomeType,HomeSize,ClothingFrequency,SustainableBrands,EnvironmentalAwareness,CommunityInvolvement,MonthlyElectricityConsumption,MonthlyWaterConsumption,Gender,UsingPlasticProducts,DisposalMethods,PhysicalActivities,Rating
0,1,35,Urban,Mostly Plant-Based,Often,Bike,Renewable,Apartment,800,Rarely,True,5,High,100,1500,Female,Rarely,Composting,High,5
1,2,28,Suburban,Balanced,Sometimes,Public Transit,Mixed,House,1500,Sometimes,True,4,Moderate,250,3000,Male,Sometimes,Recycling,Moderate,4
2,3,65,Rural,Mostly Animal-Based,Rarely,Car,Non-Renewable,House,2500,Often,False,2,Low,400,4500,Male,Often,Landfill,Low,1
3,4,42,Urban,Mostly Plant-Based,Often,Walk,Renewable,Apartment,950,Sometimes,True,4,Moderate,150,2000,Female,Rarely,Recycling,High,5
4,5,31,Suburban,Balanced,Sometimes,Public Transit,Mixed,House,1800,Often,True,3,Low,300,3500,Non-Binary,Sometimes,Combination,Moderate,3

In [3]:
sustainableLifestyle_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ParticipantID                  499 non-null    int64
 1   Age                            499 non-null    int64
 2   Location                       499 non-null    object
 3   DietType                       499 non-null    object
 4   LocalFoodFrequency             499 non-null    object
 5   TransportationMode             499 non-null    object
 6   EnergySource                   499 non-null    object
 7   HomeType                       499 non-null    object
 8   HomeSize                       499 non-null    int64
 9   ClothingFrequency              499 non-null    object
 10  SustainableBrands              499 non-null    bool
 11  EnvironmentalAwareness         499 non-null    int64
 12  CommunityInvolvement           381 non-null    object
 13  MonthlyElectricityConsumption  499 non-null    int64
 14  MonthlyWaterConsumption        499 non-null    int64
 15  Gender                         499 non-null    object
 16  UsingPlasticProducts           499 non-null    object
 17  DisposalMethods                499 non-null    object
 18  PhysicalActivities             391 non-null    object
 19  Rating                         499 non-null    int64
dtypes: bool(1), int64(7), object(12)
memory usage: 74.7+ KB

In [4]:
sustainableLifestyle_df.duplicated().sum()

np.int64(0)

In [5]:
sustainableLifestyle_df.describe()

,ParticipantID,Age,HomeSize,EnvironmentalAwareness,MonthlyElectricityConsumption,MonthlyWaterConsumption,Rating
count,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000
mean,250.024048,44.052104,1518.046092,3.062124,291.963928,3139.521042,3.430862
std,144.233925,14.904828,672.212235,1.342145,120.482275,1224.609306,1.502585
min,1.000000,18.000000,407.000000,1.000000,55.000000,536.000000,1.000000
25%,125.500000,31.000000,951.500000,2.000000,185.000000,2000.000000,2.000000
50%,250.000000,44.000000,1450.000000,3.000000,295.000000,3350.000000,4.000000
75%,374.500000,58.000000,1995.000000,4.000000,400.000000,4100.000000,5.000000
max,500.000000,96.000000,2997.000000,5.000000,498.000000,5250.000000,5.000000

In [6]:
sustainableLifestyle_df = sustainableLifestyle_df.drop(
    columns=[
        col for col in sustainableLifestyle_df.columns
        if col not in ['DietType', 'LocalFoodFrequency', 'TransportationMode', 'Rating']
        ]
    )

print(sustainableLifestyle_df)

                DietType LocalFoodFrequency TransportationMode  Rating
0     Mostly Plant-Based              Often               Bike       5
1               Balanced          Sometimes     Public Transit       4
2    Mostly Animal-Based             Rarely                Car       1
3     Mostly Plant-Based              Often               Walk       5
4               Balanced          Sometimes     Public Transit       3
..                   ...                ...                ...     ...
494   Mostly Plant-Based              Often               Walk       4
495             Balanced          Sometimes     Public Transit       2
496   Mostly Plant-Based             Always               Bike       5
497   Mostly Plant-Based             Rarely               Walk       5
498  Mostly Animal-Based             Always                Car       1

[499 rows x 4 columns]

## 2. Individual Carbon Emison Dataset

In [13]:
idvCarbonEmision_df = pd.read_csv('data/Individual_CarbonEmission.csv')
idvCarbonEmision_df.head()

,Body Type,Sex,Diet,How Often Shower,Heating Energy Source,Transport,Vehicle Type,Social Activity,Monthly Grocery Bill,Frequency of Traveling by Air,Vehicle Monthly Distance Km,Waste Bag Size,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,Energy efficiency,Recycling,Cooking_With,CarbonEmission
0,overweight,female,pescatarian,daily,coal,public,NaN,often,230,frequently,210,large,4,7,26,1,No,['Metal'],"['Stove', 'Oven']",2238
1,obese,female,vegetarian,less frequently,natural gas,walk/bicycle,NaN,often,114,rarely,9,extra large,3,9,38,5,No,['Metal'],"['Stove', 'Microwave']",1892
2,overweight,male,omnivore,more frequently,wood,private,petrol,never,138,never,2472,small,1,14,47,6,Sometimes,['Metal'],"['Oven', 'Microwave']",2595
3,overweight,male,omnivore,twice a day,wood,walk/bicycle,NaN,sometimes,157,rarely,74,medium,3,20,5,7,Sometimes,"['Paper', 'Plastic', 'Glass', 'Metal']","['Microwave', 'Grill', 'Airfryer']",1074
4,obese,female,vegetarian,daily,coal,private,diesel,often,266,very frequently,8457,large,1,3,5,6,Yes,['Paper'],['Oven'],4743

In [14]:
idvCarbonEmision_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Body Type                      10000 non-null  object
 1   Sex                            10000 non-null  object
 2   Diet                           10000 non-null  object
 3   How Often Shower               10000 non-null  object
 4   Heating Energy Source          10000 non-null  object
 5   Transport                      10000 non-null  object
 6   Vehicle Type                   3279 non-null   object
 7   Social Activity                10000 non-null  object
 8   Monthly Grocery Bill           10000 non-null  int64
 9   Frequency of Traveling by Air  10000 non-null  object
 10  Vehicle Monthly Distance Km    10000 non-null  int64
 11  Waste Bag Size                 10000 non-null  object
 12  Waste Bag Weekly Count         10000 non-null  int64
 13  How Long TV PC Daily Hour      10000 non-null  int64
 14  How Many New Clothes Monthly   10000 non-null  int64
 15  How Long Internet Daily Hour   10000 non-null  int64
 16  Energy efficiency              10000 non-null  object
 17  Recycling                      10000 non-null  object
 18  Cooking_With                   10000 non-null  object
 19  CarbonEmission                 10000 non-null  int64
dtypes: int64(7), object(13)
memory usage: 1.5+ MB

In [16]:
idvCarbonEmision_df.duplicated().sum()

np.int64(0)

In [17]:
idvCarbonEmision_df.describe()

,Monthly Grocery Bill,Vehicle Monthly Distance Km,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,CarbonEmission
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,173.875200,2031.485900,4.024600,12.139200,25.109000,11.889100,2269.147300
std,72.234018,2769.715597,1.990375,7.106369,14.698725,7.277218,1017.675247
min,50.000000,0.000000,1.000000,0.000000,0.000000,0.000000,306.000000
25%,111.000000,69.000000,2.000000,6.000000,13.000000,6.000000,1538.000000
50%,173.000000,823.000000,4.000000,12.000000,25.000000,12.000000,2080.000000
75%,237.000000,2516.750000,6.000000,18.000000,38.000000,18.000000,2768.000000
max,299.000000,9999.000000,7.000000,24.000000,50.000000,24.000000,8377.000000

In [18]:
idvCarbonEmision_df = idvCarbonEmision_df.drop(
    columns=[
        col for col in idvCarbonEmision_df.columns
        if col not in ['Diet', 'Transport', 'Vehicle Type ', 'Frequency of Traveling by Air', 'Vehicle Monthly Distance Km', 'CarbonEmission']
        ]
    )

print(idvCarbonEmision_df)

             Diet     Transport Frequency of Traveling by Air  \
0     pescatarian        public                    frequently
1      vegetarian  walk/bicycle                        rarely
2        omnivore       private                         never
3        omnivore  walk/bicycle                        rarely
4      vegetarian       private               very frequently
...           ...           ...                           ...
9995     omnivore       private                         never
9996        vegan       private                    frequently
9997   vegetarian  walk/bicycle               very frequently
9998        vegan       private                        rarely
9999  pescatarian       private                         never

      Vehicle Monthly Distance Km  CarbonEmission
0                             210            2238
1                               9            1892
2                            2472            2595
3                              74            1074
4                            8457            4743
...                           ...             ...
9995                          268            2408
9996                         5316            3084
9997                           96            2377
9998                         8688            4574
9999                         9952             826

[10000 rows x 5 columns]

## 3. Uni Student Responses Dataset

In [7]:
uniStudentResponses_df = pd.read_csv('data/UniStudentResponses.csv')
uniStudentResponses_df.head()

,Timestamp,Age group:,Education status:,Work status:,How do you travel to work/university?,"On average, how long does it take you to travel to work/university?",How engaged do you feel with the issue of climate change?,Do you know what a carbon footprint is?,How aware are you of your own carbon footprint?,How do you currently measure your own carbon footprint?,"What sources of information do you use, if any, to measure your carbon footprint?",Do you feel having more information about your carbon footprint would be useful?,Would having more information about your carbon footprint be likely to change your habits?,"What kind of motivation, if any, would you need in order to change one of your habits for a more environmentally friendly one?","How have you tried to reduce your carbon footprint, if at all?",How much do you care about trying to reduce your carbon footprint?,What do you consider to be the hardest part about trying to reduce your carbon footprint?,Have you tried to encourage others to reduce their carbon footprint?,Data Protection Agreement
0,2019/11/15 10:10:07 am GMT,18–22,In full-time education,Not working at all,Walk / Cycle,Less than 15 minutes,4,Yes,2,1,NaN,5,Maybe,An app which gives me reminders of what I coul...,I have not tried to reduce my carbon footprint,5,Effort of it ngl,No,I agree
1,2019/11/15 10:10:26 am GMT,18–22,In full-time education,Part-time,Walk / Cycle,Less than 15 minutes,3,Yes,1,1,NaN,3,Maybe,That me as a person changing something would a...,I have not tried to reduce my carbon footprint,3,I don't know what I could change,No,I agree
2,2019/11/15 10:10:33 am GMT,18–22,In full-time education,Not working at all,Walk / Cycle,Less than an hour,3,Yes,2,1,NaN,5,Maybe,Knowing where to start.,Changed how I travel,4,Not knowing where to start.,No,I agree
3,2019/11/15 10:10:43 am GMT,18–22,In full-time education,Part-time,Walk / Cycle,Less than 15 minutes,2,Yes,1,1,NaN,4,Yes,Monetary,I have not tried to reduce my carbon footprint,4,Reducing energy consumption,No,I agree
4,2019/11/15 10:10:49 am GMT,18–22,In full-time education,Not working at all,Walk / Cycle,Less than 15 minutes,2,No,1,2,NaN,2,No,enviromint,no,2,what is carbon footprint?,No,I agree

In [8]:
uniStudentResponses_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 19 columns):
 #   Column                                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                                          --------------  -----
 0   Timestamp                                                                                                                       86 non-null     object
 1   Age group:                                                                                                                      86 non-null     object
 2   Education status:                                                                                                               86 non-null     object
 3   Work status:                                                                                                                    86 non-null     object
 4   How do you travel to work/university?                                                                                           86 non-null     object
 5   On average, how long does it take you to travel to work/university?                                                             86 non-null     object
 6   How engaged do you feel with the issue of climate change?                                                                       86 non-null     int64
 7   Do you know what a carbon footprint is?                                                                                         86 non-null     object
 8   How aware are you of your own carbon footprint?                                                                                 86 non-null     int64
 9   How do you currently measure your own carbon footprint?                                                                         86 non-null     int64
 10  What sources of information do you use, if any, to measure your carbon footprint?                                               3 non-null      object
 11  Do you feel having more information about your carbon footprint would be useful?                                                86 non-null     int64
 12  Would having more information about your carbon footprint be likely to change your habits?                                      86 non-null     object
 13  What kind of motivation, if any, would you need in order to change one of your habits for a more environmentally friendly one?  84 non-null     object
 14  How have you tried to reduce your carbon footprint, if at all?                                                                  85 non-null     object
 15  How much do you care about trying to reduce your carbon footprint?                                                              86 non-null     int64
 16  What do you consider to be the hardest part about trying to reduce your carbon footprint?                                       84 non-null     object
 17  Have you tried to encourage others to reduce their carbon footprint?                                                            86 non-null     object
 18  Data Protection Agreement                                                                                                       86 non-null     object
dtypes: int64(5), object(14)
memory usage: 12.9+ KB

In [9]:
uniStudentResponses_df.duplicated().sum()

np.int64(0)

In [10]:
uniStudentResponses_df.describe()

,How engaged do you feel with the issue of climate change?,How aware are you of your own carbon footprint?,How do you currently measure your own carbon footprint?,Do you feel having more information about your carbon footprint would be useful?,How much do you care about trying to reduce your carbon footprint?
count,86.000000,86.000000,86.000000,86.000000,86.000000
mean,3.162791,2.267442,2.034884,3.895349,3.348837
std,1.136149,1.202198,1.182696,1.063060,1.060160
min,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3.000000,1.000000,1.000000,3.000000,3.000000
50%,3.000000,2.000000,2.000000,4.000000,3.000000
75%,4.000000,3.000000,3.000000,5.000000,4.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000

In [11]:
uniStudentResponses_df = uniStudentResponses_df.drop(
    columns=[
        col for col in uniStudentResponses_df.columns
        if col not in ['How do you travel to work/university?', 'On average, how long does it take you to travel to work/university?']
        ]
    )

uniStudentResponses_df = uniStudentResponses_df.rename(columns={
    'How do you travel to work/university?': 'transportationToTravel',
    'On average, how long does it take you to travel to work/university?': 'avarageDistanceToTravel'
})

print(uniStudentResponses_df)

                      transportationToTravel avarageDistanceToTravel
0                               Walk / Cycle    Less than 15 minutes
1                               Walk / Cycle    Less than 15 minutes
2                               Walk / Cycle       Less than an hour
3                               Walk / Cycle    Less than 15 minutes
4                               Walk / Cycle    Less than 15 minutes
..                                       ...                     ...
81                              Walk / Cycle    Less than 15 minutes
82                  Walk / Cycle;Bus / Train       Less than an hour
83  Walk / Cycle;Car / Motorbike;Bus / Train    Less than 15 minutes
84                  Walk / Cycle;Bus / Train    Less than 15 minutes
85                              Walk / Cycle    Less than 15 minutes

[86 rows x 2 columns]